### PR TITLE
build: auto publish releases

### PR DESCRIPTION
**Pull request by keithamus**
### What?

Add a CI script to publish packages automatically for us.

### Why?

We've had difficulty in the past with publishing things in a reliable way. Forcing devs to publish on their local machines can mean all sorts of things:

 - Perhaps they fail to run a command like `npm ci` which means deps are out of date, if compiling code this can affect the published artefact.
 - Perhaps they've got extra files in their repository such as editor session files or notes files or unstaged files - this can sometimes accidentally get included
 - We aren't always the best at setting up the dual-publish workflow, publishing to both GPR and npm. So some packages get inconsistently published to one or the other.
 - Publishing packages can be scary! What if I missed something? It's a nerve wracking experience!

Additional pains can be:
 - We have to provision entitlements. As new people join they need to be set up on github/npm, as people depart they need to be removed reliably. More systems to maintain

All of these issues can be solved by simply getting the computer to do it. In this case GitHub Actions. It gives us:
 - A reliable and repeatable environment
 - A single user/scope/authority to publish from
 - An easy user interface to handle publishes from (the GitHub Releases page)

### How?

This CI script will, on creation of a GitHub release:

 - Install deps with `npm ci`
 - Run tests just to make sure this release is A-OK
 - Set the package.json version to the releases tag
 - Publish to both npm and GPR

If we like this idea we can push this out to all other repos.

### Tradeoffs

One downside to this particular style of doing things is that the in-version-control `package.json#version` key will be out of sync with what is published. [On projects where I automate this I set that key to `0.0.0-dev` so people know something funky is going on](https://github.com/keithamus/sort-package-json/blob/master/package.json#L3).

### CODE REVIEW

**Review by koddsson — APPROVED** [review]
> One downside to this particular style of doing things is that the in-version-control `package.json#version` key will be out of sync with what is published. [On projects where I automate this I set that key to `0.0.0-dev` so people know something funky is going on](https://github.com/keithamus/sort-package-json/blob/master/package.json#L3).

I don't like this but I think the benefits far outweigh my small nitpick.

Looks good to me ✨

**Comment by smockle** [comment]
> ### Tradeoffs
> One downside to this particular style of doing things is that the in-version-control `package.json#version` key will be out of sync with what is published. [On projects where I automate this I set that key to `0.0.0-dev` so people know something funky is going on](https://github.com/keithamus/sort-package-json/blob/master/package.json#L3).

I wrote a GitHub Action to bump the `package.json` version for personal projects I auto-publish: https://github.com/smockle/action-version ([example workflow](https://github.com/smockle/contrast/blob/5fadbe3a473a404316029aa9a7276ae841482c1c/.github/workflows/publish.yml#L27-L31))

Would we want to use a similar approach here?

**Comment by JoseInTheArena** [comment]
Tying together 
>All of these issues can be solved by simply getting the computer to do it. In this case GitHub Actions. It gives us:

and

>One downside to this particular style of doing things is that the in-version-control package.json#version key will be out of sync with what is published. On projects where I automate this I set that key to 0.0.0-dev so people know something funky is going on.

and

>I wrote a GitHub Action to bump the package.json version for personal projects I auto-publish: https://github.com/smockle/action-version (example workflow)

I wonder if bumping the version could be part of the same action that's doing the publishing. Also, if I recall correctly that's something a tool like [Lerna](https://github.com/lerna/lerna/tree/main/commands/publish) (NOTE: not saying we should use that 😄 ) handles pretty well. It could be inspiration.

**Comment by keithamus** [comment]
> bump the `package.json` version
> bumping the version

There's a few different ideas  here, so I'd like to clarify the options we have:

 1. Increment the version number based on some criteria. @smockle links to an action which runs `npm version patch` - which bumps the `n.n.X` version for each `commit`. Another example of this concept is [Semantic Release](https://semantic-release.gitbook.io/semantic-release/). For this we'd need to add tooling to determine which segment of the version number to increment, or always increment only one segment.
 2. Automate the publishing of the package based on a pre-authored version number. That's what this PR does, or as @JoseInTheArena suggests - what Lerna can do. For this we need to supply the version number to trigger a release.

I've opted for 2. here because it's the least amount of change. It takes something that is currently difficult (reliably publishing the artefact) and automates it away. Picking the version number (what 1. does) is something we can A) work out later, B) isn't a bottleneck for us now.

---

I'm pretty confident with what we have now, so I'll merge it and we can try it for a while. If folks are dissatisfied we can always revert :slightly_smiling_face:

**Pull request merged**
